version: '3.4'

services:
  supermarket.api:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ConnectionString=Server=${SERVER};Database=${SQL_DB};User ID=${USER};Password=${PASSWORD};Encrypt=False;MultipleActiveResultSets=True;TrustServerCertificate=True;

    ports:
        - "9000:8080"

    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro